name: Databricks Bundle Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"
      # Sử dụng @main để tránh lỗi "unable to find version"
      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      - name: Deploy Bundle
        run: databricks bundle deploy -t dev
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      # :white_check_mark: 5. Notify SUCCESS
      # - name: Notify Slack Success
      #   if: success()
      #   run: |
      #     curl -X POST -H "Content-type: application/json" \
      #     --data "{\"text\":\":white_check_mark: Deploy by Git Action to Env.Dev SUCCESS By ${{ github.actor }}\"}" \
      #     ${{ secrets.SLACK_WEBHOOK }}

      # # :x: 6. Notify FAIL (khuyên thêm)
      # - name: Notify Slack Failure
      #   if: failure()
      #   run: |
      #     curl -X POST -H "Content-type: application/json" \
      #     --data "{\"text\":\":x: Deploy FAILED by ${{ github.actor }}\"}" \
      #     ${{ secrets.SLACK_WEBHOOK }}